### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by featureoverload** [RDpWTeHM/Embedded-GUI-Develop#1]
- [ ] make install 的 python install  和 *.cgi; *.html install 区分。
- [ ] python 库的 `touch sdist` solution 没有起到作用。pending...

==== Done: 

- [x] flate API 向下兼容
- [x] CGIDebugLogd 切换输出终端。
- [x] CGIDebugLogd 使用 python-daemon solution
- [x] README.md 的 `$ make Include` 说明！
- [x] debug Log 输出 API 简化， merge solution from hello-CGIDebugLog.c to CGIDebugLogc.c 
- [x] mini_httpd.conf patch 
- [x] SYNC
- [x] CGIDebugLogd: daemonEcho2 指定 CGIDebugLogd.py 路径启动

**Comment by featureoverload** [comment]
**“CGIDebugLogd 使用 python-daemon solution”** 
  使用 C 原因编写 daemonEcho2 程序来使 CGIDebugLogd.py daemon 化，原先是因为 python-daemon solution 在低性能主机（如 Raspberry Zero）上运行太慢（启动该进程的时间太长），所以使用 C 语言方案。
  使用 C 语言在对错误处理上会有写障碍，并且本 github 上的 Embedded-GUI-Develop 假象的工作环境为“老”台式机，或虚拟机，所以性能方面不会有上述问题。
   所以，预期会默认使用 python-daemon 的方案。
